### ISSUE TITLE
0 RX with pkt-gen on patched ixgbe interface.

### ISSUE THREAD

**Issue by jmhelt** [luigirizzo/netmap#344] opened 2017-08-01 20:36 UTC
I am seeing an issue where I am able to transmit on an interface but not receive when using pkt-gen. My machine is running Ubuntu 16.04 with kernel version  `4.4.0-75-generic` and the latest master of netmap. The NIC is an Intel x520 dual port device. Below is the output on the receiver side. I simultaneously ran a second instance of pkt-gen transmitting on the same interface.
```
~# pkt-gen -i enp129s0f0 -f rx
749.741210 main [2635] interface is enp129s0f0
749.741257 main [2755] using default burst size: 512
749.741302 main [2763] running on 1 cpus (have 32)
749.741662 extract_ip_range [462] range is 10.0.0.1:1234 to 10.0.0.1:1234
749.741677 extract_ip_range [462] range is 10.1.0.1:1234 to 10.1.0.1:1234
750.317548 main [2858] mapped 334980KB at 0x7f3ce6540000
Receiving from netmap:enp129s0f0: 32 queues, 1 threads and 1 cpus.
750.317625 start_threads [2317] Wait 2 secs for phy reset
752.317693 start_threads [2319] Ready...
752.317809 receiver_body [1706] reading from netmap:enp129s0f0 fd 3 main_fd 3
753.318794 main_thread [2407] 0.000 pps (0.000 pkts 0.000 bps in 1001031 usec) 0.00 avg_batch 0 min_space
754.319824 main_thread [2407] 0.000 pps (0.000 pkts 0.000 bps in 1001030 usec) 0.00 avg_batch 99999 min_space
755.320859 main_thread [2407] 0.000 pps (0.000 pkts 0.000 bps in 1001035 usec) 0.00 avg_batch 99999 min_space
...
```
As a sanity check, I tried transmitting on a separate interface to ensure that packets were actually making it to the wire (output below) and configured packets to loop back to the second port. I have ensured that I can see packets are making it back to the receiver interface (using tcpdump).
```
~$ pkt-gen -i enp129s0f1 -f tx -S 90:e2:ba:84:d6:49 -D 90:e2:ba:84:d6:48
752.930054 main [2635] interface is enp129s0f1
752.930101 main [2755] using default burst size: 512
752.930134 main [2763] running on 1 cpus (have 32)
752.930222 extract_ip_range [462] range is 10.0.0.1:1234 to 10.0.0.1:1234
752.930231 extract_ip_range [462] range is 10.1.0.1:1234 to 10.1.0.1:1234
753.505579 main [2858] mapped 334980KB at 0x7f051a0d6000
Sending on netmap:enp129s0f1: 32 queues, 1 threads and 1 cpus.
10.0.0.1 -> 10.1.0.1 (90:e2:ba:84:d6:49 -> 90:e2:ba:84:d6:48)
753.505605 main [2955] Sending 512 packets every  0.000000000 s
753.505630 start_threads [2317] Wait 2 secs for phy reset
755.505722 start_threads [2319] Ready...
755.505828 sender_body [1505] start, fd 3 main_fd 3
755.527551 sender_body [1587] drop copy
756.506835 main_thread [2407] 14.663 Mpps (14.679 Mpkts 7.046 Gbps in 1001038 usec) 289.14 avg_batch 0 min_space
757.507893 main_thread [2407] 14.880 Mpps (14.896 Mpkts 7.150 Gbps in 1001059 usec) 300.68 avg_batch 99999 min_space
758.508959 main_thread [2407] 14.881 Mpps (14.897 Mpkts 7.150 Gbps in 1001064 usec) 296.96 avg_batch 99999 min_space
```

I have also disable the various offload settings for both devices using `ethtool` as was mentioned in the README. Any suggestions on what to try next?

I'm not sure if its relevant to this issue, but the pkt-gen programs (both sender and receiver) periodically get into a state where they cannot be killed.

**Comment by jmhelt** [comment] 2017-08-01 20:57
Also since it may be helpful, here is some relevant output from the kernel log. I find it strange that the device in question (enp129s0f0) is not mentioned like enp129s0f1.
```
# dmesg | grep netmap
[  620.419008] 795.220415 [3403] netmap_init               run mknod /dev/netmap c 10 55 # error 0
[  620.428854] netmap: loaded module
[  634.324424] net eth0: netmap queues/slots: TX 32/512, RX 32/512
[  634.705219] net enp129s0f1: netmap queues/slots: TX 32/512, RX 32/512
```

**Comment by tbarbette** [comment] 2017-09-12 09:40
I run into the same problem. I tried to revert before the TD write back update and it does not change a thing.
I used pktgen and FastClick. Pktgen gives me : 
main_thread [2465] 0.000 pps (0.000 pkts 0.000 bps in 1001037 usec) 0.00 avg_batch 99999 min_space
Eventually lead to softlock : 
Message from syslogd@sam at Sep 12 11:39:13 ...
 kernel:[ 3121.244566] NMI watchdog: BUG: soft lockup - CPU#14 stuck for 22s! [pkt-gen:28489]
With FastClick I saw that I receive a few good packets then 0-size packets. Like if nm_ring_space returned actually too much space.

**Comment by giuseppelettieri** [comment] 2017-09-12 11:12
Does it change anything if you use an older ixgbe driver?

make distclean
cat >config.mak <<'EOF'
$(call enabled_intel_driver,ixgbe,4.2.1)
EOF
./configure

**Comment by tbarbette** [comment] 2017-09-12 16:17
The command does not seem to work. ixgbe is just not compiled anymore.

**Comment by tbarbette** [comment] 2017-09-12 16:22
Hi again,
It compiled with 4.5.4.
And both pkt-gen and (Fast)Click work correctly. So one of the latest version indeed causes the problem.

**Comment by giuseppelettieri** [comment] 2017-09-12 16:24
Thanks, that is very useful information!

**Comment by weinrank** [comment] 2017-09-13 16:45
Hey,
I'm using netmap on FreeBSD 12 current and I'm facing a similar problem:
When using the Intel 10G NIC (ix driver) everything works fine but when I'm using the Intel 1G NIC (igb driver) netmap does not receive any packets.

I'll test it on Stable machine and provide more details.

**Comment by giuseppelettieri** [comment] 2017-09-22 10:06
Hi @tbarbette and possibly also @jmhelt, may you try the path provided in #355 ?

I am not sure that the problem seen by @weinrank  is actually the same.

**Comment by petero** [comment] 2017-10-04 19:14
I have the same problem on Debian 8 with ixgbe 5.4.2 and 5.4.3.

**Comment by giuseppelettieri** [comment] 2017-10-09 09:13
Hi @petero, does the the patch in #355 changes anything? (Beware: IOMMU must be kept disabled for ixgbe for now, even with the latest master)

**Comment by petero** [comment] 2017-10-09 13:38
Is it possible to disable IOMMU in the driver ? Or only in grub ?

**Comment by giuseppelettieri** [comment] 2017-10-11 11:27
Hi @petero. You need to disable it in grub and reboot.

**Comment by giuseppelettieri** [comment] 2017-10-16 09:57
Update: the current master already includes the patch in #355 and also fixes an initialization bug that was introduced after recent ixgbe updates. Any testing is very much appreciated!

**Comment by petero** [comment] 2017-10-16 10:56
IOMMU disabled in grub, latest commit from master 1597e0c with ixgbe 5.2.3, still hangs kernel.

/usr/src/netmap/build-apps/pkt-gen# ./pkt-gen -i eth2 -f rx
568.412369 main [2702] interface is eth2
568.412409 main [2827] using default burst size: 512
568.412436 main [2835] running on 1 cpus (have 16)
568.412964 extract_ip_range [464] range is 10.0.0.1:1234 to 10.0.0.1:1234
568.412983 extract_ip_range [464] range is 10.1.0.1:1234 to 10.1.0.1:1234
568.413008 nm_open [856] overriding ARG1 0
568.413016 nm_open [860] overriding ARG2 0
568.413021 nm_open [864] overriding ARG3 0
568.413025 nm_open [868] overriding RING_CFG
568.413030 nm_open [877] overriding ifname eth2 ringid 0x0 flags 0x8001

I will provide more debug, after a physical restart of the server.

**Comment by giuseppelettieri** [comment] 2017-10-16 11:55
Hi @petero, thanks for reporting. However, this issue is about ixgbe not receving, while you seem to have a different problem (the kernel hangs). Please find a more suitable issue or open a new one.

**Comment by petero** [comment] 2017-10-16 12:00
There are already 3 issues regarding ixgbe, pkt-gen crash #344 #355 and #345. I will get additional info and add new isssue or update one of those.

**Comment by vmaffione** [comment] 2017-12-15 14:03
Can we close this?

**Comment by jmhelt** [comment] 2017-12-17 02:51
If you all don't need it for tracking, then ok by me.

**Comment by vmaffione** [comment] 2017-12-18 18:43
as code changed since this issue was opened, I was just wondering if this is still reproducible. If not we can close it

**Comment by taozx** [comment] 2017-12-27 01:43
@giuseppelettieri 
make distclean
cat >config.mak <<'EOF'
$(call enabled_intel_driver,ixgbe,4.2.1)
EOF
./configure

I use there command,and also complie with ixgbe 5.3.3.
what's the problem?

**Comment by giuseppelettieri** [comment] 2017-12-27 08:41
If you are using the latest master, changing the driver version is simpler. Just do as follows:
```
make distclean
./configure --select-version=ixgbe:4.2.1
```

**Closed** 2018-10-12 09:38 UTC
Labels: bug
