### ISSUE TITLE
Question about performance expectations

### ISSUE THREAD

**Issue by sqwishy** [luigirizzo/netmap#384] opened 2017-10-25 22:44 UTC
I'm using pkt-gen to measure netmap performance on a machine running Linux with a E3845 CPU and 82583V NIC. I can reach line rate (1G) using large packets when sending to itself but am CPU bound when sending 64 byte packets.

Affinities are set to different cores for sending and receiving.
I'm using the e1000e driver with netmap patches.
CPU governor is set to performance for all four cores.

I'm only seeing aroud 971 Kpps sending and 1.184 Mpps receiving. I'd expect something like 1.4 Mpps. Most (about 85%) of the CPU time is in kernel, with a small amount in irq and user. The test setup is such that my device is sending on one interface and receiving on different interface on the same NIC on the same machine.

Is there something I am overlooking? Is it possible that this NIC is just not terribly speedy? Would that show up as being CPU bound caught up in the kernel?

**Comment by vmaffione** [comment] 2017-10-26 06:18
Have you loaded the patched e1000e modules?
Can you show the pktgen commands you are using on the sender and receiver?

**Comment by sqwishy** [comment] 2017-10-26 06:45
I did load the modules. To be sure, I built them with -netmap suffix and saw they were loaded with lspci:
```
03:00.0 Ethernet controller: Intel Corporation 82583V Gigabit Network Connection
...
        Kernel driver in use: e1000e-netmap
```

The commands I'm testing with are `pkt-gen -i eth1 -f tx -l 64 -a1` and `pkt-gen -i eth2 -f rx -a2`.

**Comment by vmaffione** [comment] 2017-10-26 07:18
Ok, so the configuration seems correct. Just to make sure, check that you don't have messages like these in the kernel log
````
992.882232 [1259] generic_netmap_attach     Emulated adapter for enp1s0f1 created (prev was           (null))
[49147.778708] 992.912247 [ 444] generic_netmap_register   Emulated adapter for enp1s0f1 activated
[49147.778738] 992.912278 [ 489] generic_netmap_register   Emulated adapter: ring 'enp1s0f1 RX0' activated
[49147.778748] 992.912288 [ 496] generic_netmap_register   Emulated adapter: ring 'enp1s0f1 TX0' activated
[...]
````
Does anything change if you remove the -a option? maybe the two pkt-gen end up running on the same core (different hyperthreads). You should try to pin them to different cores (e.g. 0 and 1 on linux).
How much CPU utilization do you see for each of the two pkt-gen processes?
You should also doublecheck the interrupt rate in /proc/interrupts, to make sure it's not too high.
Also, remove any TX/RX flow control on the two interfaces, using ethtool:
````
$ sudo ethtool -A eth1 tx off rx off
$ sudo ethtool -A eth2 tx off rx off
````

**Comment by sqwishy** [comment] 2017-10-26 07:56
>check that you don't have messages like these in the kernel log

Nothing like that in dmesg, a lot of
```
[48939.721215] e1000e_netmap: eth1 NIC Link is Down
[48942.162375] e1000e_netmap: eth1 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: Rx/Tx
[48942.170101] e1000e_netmap: eth2 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: Rx/Tx
```

>Does anything change if you remove the -a option?

Performance doesn't change if I use `-a0` on the sender instead of core 1. Same if I remove the option entirely. Results are the same; about 971ish Kpps on the sender.

>How much CPU utilization do you see for each of the two pkt-gen processes?

With affinities set to 0 and 2, the sender is pinned to a core and the the receiver sits at around 50%. Here is some output from `mpstat` that might help:
```
Average:     CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
Average:     all    2.64    0.00   30.86    0.00    0.00    3.90    0.00    0.00    0.00   62.60
Average:       0    5.02    0.00   80.72    0.00    0.00   13.86    0.00    0.00    0.00    0.40
Average:       1    0.40    0.00    0.20    0.00    0.00    0.00    0.00    0.00    0.00   99.40
Average:       2    6.48    0.00   49.38    0.00    0.00    0.31    0.00    0.00    0.00   43.83
Average:       3    0.20    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   99.80
```

>You should also doublecheck the interrupt rate in /proc/interrupts, to make sure it's not too high.

Not entirely sure what I'm looking at/for here, so I might have to get back to you. But the numbers for Local and Rescheduling interrupts are each lower than the interface interrupt for each CPU0 and CPU2.

>Also, remove any TX/RX flow control on the two interfaces, using ethtool:

Oh yeah, I saw that in the README but was confused when I tried earlier.
```
# ethtool -A eth2 tx off rx off
# ethtool -a eth2
Pause parameters for eth2:
Autonegotiate:  on
RX:             on
TX:             on
# ethtool -A eth1 tx off rx off
# ethtool -a eth1
Pause parameters for eth1:
Autonegotiate:  on
RX:             on
TX:             on
```
This isn't what I expected, I figured the NIC didn't support whatever I was trying to do?

**Comment by vmaffione** [comment] 2017-10-26 08:15
You can use something like `watch -n1 'grep eth1 /proc/interrupts'` to monitor interrupt rate on eth1 (You need to observe how the counter increase per-second and compute the difference). You should check that both TX interrupts and RX interrups on eth1 and eth2 are not too much (e.g. more than 30-50K).

I can see from your CPU utilization stats that the core where the sender runs (core 0) is 100% busy.
So it seems you are CPU bound, which is weird. But maybe the problem is that you are using an ATOM CPU, which is way slower than the i5/i7 we usually use.
If the sender core is 100% busy then TX/RX ethernet flow control shouldn't be the issue (as you are not I/O bound).
What is the average batch reported by pkt-gen (sender and receiver)? In any case the receiver seems ok, it's only 50% busy, while the bottleneck is clearly on the sender.

**Comment by sqwishy** [comment] 2017-10-26 16:26
>You should check that both TX interrupts and RX interrupts on eth1 and eth2 are not too much

Sender on eth1 increases by about 20K/s the receiver on eth2 the same.

>What is the average batch reported

The sender reports 5, and the receiver about 8.3.

>maybe the problem is that you are using an ATOM

Yeah, that's what I figured it might be important. The site alleges 10G line rate on 1.7 Ghz but it doesn't say what CPU that was on. I would be surprised if there wasn't a difference in performance between an atom and a xeon with the same clock speed.

**Comment by vmaffione** [comment] 2017-10-26 17:11
A sender batch of 5 is a suggestion that actually you are slowed down by the nic.. it should be way higher. Does it change anything if you use pkt-gen-b on the sender side?It's just the busy wait version of pktgen.

**Comment by sqwishy** [comment] 2017-10-26 19:55
`pkt-gen-b` reports a batch size of just under 4; `491.156126 main_thread [2467] 976.193 Kpps (977.303 Kpkts 500.379 Mbps in 1001137 usec) 3.93 avg_batch 99999 min_space` assuming I'm reading that right. And the core is still pinned but entirely in the kernel instead of a bit soft-irq.

I guess a slow NIC would show up as high CPU usage in kernel if the kernel is waiting on the device?

**Comment by vmaffione** [comment] 2017-10-26 20:14
No, the "wait" does not show up as CPU wasted in kernel space. Your application does wait by means of poll()/select(), freeing the CPU for other tasks (almost none in your scenario).
From one side a slow NIC would cause the application to go to sleep often, and so the CPU utilization to be less than 100%.
On the other hand a slow NIC can cause the batch to shrink because each time the application wakes up it finds that only a few slots are free (because the NIC is slow to free them). A small batch means more per-packet overhead.
Depending on the particular timing of your hardware/software, you can end up into unfavourable situations.

You may try add a usleep() in the sender to artificially increase the batch, e.g.:
````
diff --git a/apps/pkt-gen/pkt-gen.c b/apps/pkt-gen/pkt-gen.c
index 6418d68c..fd277933 100644
--- a/apps/pkt-gen/pkt-gen.c
+++ b/apps/pkt-gen/pkt-gen.c
@@ -1581,6 +1581,7 @@ sender_body(void *data)
                        goto quit;
                }
 #else /* !BUSYWAIT */
+               usleep(50);
                if (poll(&pfd, 1, 2000) <= 0) {
                        if (targ->cancel)
                                break;
````
By playing with the usleep parameters you can see if there is a range of values that causes the average batch to grow (and so the throughput to increase).

**Comment by sqwishy** [comment] 2017-10-26 20:28
Right, that makes sense. Adding a usleep(40) increases the patch size to 127.5 and decreases CPU load significantly. But throughput does not change. I'll try a few other things; but if throughput is stable, that would suggest that NIC can't move the packets any faster, right?

Instead of sleeping is it possible to configure the device to send an interrupt less frequently so that things are batched a little more? Or is that something that the application would do best?

**Comment by sqwishy** [comment] 2017-10-26 20:47
In fact, throughput does go up a bit to around 1.150 Mpps with `usleep(25)`. So that's interesting. It's not line rate but it's better than what it was previously and with lower CPU usage.

**Comment by vmaffione** [comment] 2017-10-26 21:47
Yes you should be able to play with ethtool to change the tx interrupt moderation setting, if your nic supports that. Now it's clear that you are i/o bound, but this is masked by unfavourable operting regime in terms of syscall and interrupt

**Comment by vmaffione** [comment] 2017-10-26 21:49
... average number of interrupt and syscall per packet. Because of rhe infavourable regime, both cpu utilization and throughput are not optimal.

**Comment by vmaffione** [comment] 2017-11-01 08:51
Closing this for now

**Closed by vmaffione** 2017-11-01 08:51 UTC
Labels: question
