### ISSUE TITLE
epoll does not return if data already flowing before opening interface

### ISSUE THREAD

**Issue by bmerry** [luigirizzo/netmap#171] opened 2016-04-26 20:37 UTC
This might be related to #102, although in my case the problem is specific to epoll. I've written a small test receiver (attached) to demonstrate the issue. It loops forever, alternatively doing
1. `epoll_wait` to wait for packets to become available
2. loop over the rings counting packets and resetting the head and cur pointers.
If I start this listener running, then start flooding it with 100Kpps, then it works fine. If I start the packet flood first, then it receives a small number of batches and then `epoll_wait` doesn't return again.

Behaviour is slightly different depending on whether I use the i40e driver, or the generic driver (same interface, but loading kernel's i40e.ko instead of netmap's version). With the i40e driver, I typically see this:

```
Done sleeping
batch of 503 packets
```

With the generic driver, the output varies a little more. A common output is

```
Done sleeping
batch of 511 packets
batch of 511 packets
batch of 3 packets
```

although I've seen larger numbers of batches before it fails.

The packet flood is generated from another machine on a 40GbE network using

```
sudo ./pkt-gen -f tx -R 100000 -l 64 -i p5p1
```

The receiver machine is Ubuntu 14.04, running Linux 4.4.0-18-generic #34~14.04.1-Ubuntu, and netmap 77df06a (latest as of today).

Sample code below (the interface name is hardcoded). Changing `USE_EPOLL` to 0 to use `poll()` makes everything work again, which is why I think the problem is somehow epoll-related.

``` c++
#define NETMAP_WITH_LIBS
#include <iostream>
#include <cassert>
#include <net/netmap_user.h>
#include <sys/epoll.h>
#include <sys/poll.h>

using namespace std;

#define USE_EPOLL 1

int main()
{
    nm_desc *desc = nm_open("netmap:p5p1", NULL, 0, NULL);
    assert(desc);
    sleep(2);
    cout << "Done sleeping" << endl;
#if USE_EPOLL
    int epoll_fd = epoll_create1(EPOLL_CLOEXEC);
    assert(epoll_fd != -1);
    epoll_event event;
    event.events = EPOLLIN;
    event.data.ptr = NULL;
    epoll_ctl(epoll_fd, EPOLL_CTL_ADD, desc->fd, &event);
#else
    pollfd fds[1] = {};
    fds[0].fd = desc->fd;
    fds[0].events = POLLIN;
#endif
    while (true)
    {
#if USE_EPOLL
        int ret = epoll_wait(epoll_fd, &event, 1, -1);
#else
        int ret = poll(fds, 1, -1);
#endif
        assert(ret == 1);
        int packets = 0;
        for (int ri = desc->first_rx_ring; ri <= desc->last_rx_ring; ri++)
        {
            netmap_ring *ring = NETMAP_RXRING(desc->nifp, ri);
            for (unsigned int i = ring->cur; i != ring->tail; i = nm_ring_next(ring, i))
            {
                packets++;
            }
            ring->cur = ring->head = ring->tail;
        }
        cout << "batch of " << packets << " packets" << endl;
    }
    nm_close(desc);
    return 0;
}
```

**Comment by sethhall** [comment] 2016-06-30 20:21
I believe this problem has to do with netmap not supporting epoll yet.  The internal pointers aren't being updated correctly during the epoll so what you are seeing is no packets being available because none of the buffers are being released back to netmap.

The difference in the number of packets likely just has to do with the queue lengths depending on how you are opening the NIC.

@giuseppelettieri, I suspect this ticket can be closed since it's just related to epoll not being available. (hope I got this all right!)

**Comment by bmerry** [comment] 2016-07-06 08:02
The netmap man-page claims that epoll is supported:

     netmap supports both non-blocking I/O through ioctls(), synchronization
     and blocking I/O through a file descriptor and standard OS mechanisms
     such as select(2), poll(2), epoll(2), kqueue(2).

**Comment by vmaffione** [comment] 2016-07-06 14:04
Hi,
  There is an optimization in the netmap_poll() function that may prevent epoll() to work correctly. Could you please 
[poll.patch.txt](https://github.com/luigirizzo/netmap/files/349945/poll.patch.txt)

try the attached patch?

**Comment by bmerry** [comment] 2016-07-06 14:06
I don't have ready access to an i40e card at the moment, but hopefully I'll be able to plug one in in a week or two and give it a test.

**Comment by vmaffione** [comment] 2016-07-06 14:11
Thanks! Even without physical NICs you could run your program to receive from a VALE port, while traffic is generated using pkt-gen on a different VALE port (on the same VALE switch).

**Comment by bmerry** [comment] 2016-07-26 12:04
I just tried applying the patch against c104b27, using the generic driver. With epoll, I still get
```
Done sleeping
batch of 511 packets
batch of 511 packets
batch of 3 packets
```
and then it stops triggering. So the patch doesn't seem to have fixed it. This is a different machine to last time, but I confirmed that using plain poll() still works.

**Comment by vmaffione** [comment] 2016-07-27 17:30
Hi,
  You are right the previous patch does not fix it, I can reproduce your problem in a similar configuration.

However, there was one bit missing, related to a sort of optimization. Can you try the following improved patch? It does work for me, using your program above.

[poll2.patch.txt](https://github.com/luigirizzo/netmap/files/386713/poll2.patch.txt)

**Comment by bmerry** [comment] 2016-07-28 08:47
@vmaffione that patches seems to do the trick - at least with the generic driver. I don't have a machine to experiment on with an i40e card, but I think once the patch is committed you can close this bug and I'll re-open if I run into the problem with the i40e driver in future.

**Comment by vmaffione** [comment] 2016-07-28 18:25
Yes, I'm pretty sure this patch is ok, the issue with epoll is that a selrecord/poll_wait is required each time netmap_poll() is called. You can use this patch in the meanwhile we discuss this changes internally.

**Comment by gl000008** [comment] 2017-08-25 15:42
Hi,
It has been a while since this temporal patch was generated. Is epoll supported now in the latest commit (c7b8f65)?

**Comment by vmaffione** [comment] 2017-08-26 04:33
We still don't, but it's time to fix this. Have you done some experiment with epoll() and tried the patch?

**Comment by gl000008** [comment] 2017-08-26 12:48
I am still having problems with poll and the "bridge" application on the latest commit (once they are solved I will try with epoll).

**Comment by vmaffione** [comment] 2017-08-26 22:31
which problems do you have with poll?

**Comment by vmaffione** [comment] 2017-12-12 08:34
Hi,
  Now `poll_wait()` is called unconditionally on Linux. Can somebody check if `epoll` applications are working correctly on current master?

**Comment by bmerry** [comment] 2017-12-12 11:11
Unfortunately we're no longer using any i40e cards (or netmap), so I'm not in a position to test this.

**Comment by vmaffione** [comment] 2017-12-14 09:29
Ok, thanks. As far as I can tell now `epoll` is working (your example above is working in my tests), so I'm closing this. Please reopen if necessary.

**Closed by vmaffione** 2017-12-14 09:29 UTC
