### ISSUE TITLE
Netmap on BananaPi

### ISSUE THREAD

**Issue by sasukeskapa** [luigirizzo/netmap#76] opened 2015-08-24 10:09 UTC
We try to run netmap on a BananaPi switch/router, but we can't get it to compile.
We use Bananian Linux 3.4.104 and ran these commands:
<b>cd path/netmap/LINUX
./configure --kernel-sources=/home/downloads/linux-bananapi
make SRC=/home/downloads/linux-bananapi KSRC=/usr/src/linux-headers-3.4.104-bananian apps </b>
(We got the kernel sources downloaded in the "/home/downloads/linux-bananapi" folder.)
The "configure" seems to finish without problems, but the "make" gives errors (we included the output below). We also tried it without compiling the apps (we included the output below) and it didn't give us any errors, but we couldn't test it without the apps properly. (We tried the ovs patch, but that didn't work, so we did the patching manually and tried testing it with that, but it didn't accelerate it.)(Also the ovs patch didn't match the source code of OVS. (We checked version v2.3.2, v2.3.1 and the current master.))

<b> ./configure --kernel-sources=/home/downloads/linux-bananapi </b>
*********************************\* WARNING **********************************
**\* CONFIG_IXGBE not set in /lib/modules/3.4.104-bananian/build/.config, skipping ixgbe

---

*********************************\* WARNING **********************************
**\* CONFIG_IGB not set in /lib/modules/3.4.104-bananian/build/.config, skipping igb

---

*********************************\* WARNING **********************************
**\* CONFIG_E1000E not set in /lib/modules/3.4.104-bananian/build/.config, skipping e1000e

---

*********************************\* WARNING **********************************
**\* CONFIG_E1000 not set in /lib/modules/3.4.104-bananian/build/.config, skipping e1000

---

*********************************\* WARNING **********************************
**\* CONFIG_FORCEDETH not set in /lib/modules/3.4.104-bananian/build/.config, skipping forcedeth.c

---

*********************************\* WARNING **********************************
**\* CONFIG_VIRTIO_NET not set in /lib/modules/3.4.104-bananian/build/.config, skipping virtio_net.c

---

*********************************\* WARNING **********************************
**\* 'r8169.c': no applicable patch found and no override file provided.
**\* Disabling driver.

---

kernel directory            /lib/modules/3.4.104-bananian/build
linux version               30468  [3.4.104]
module file                 netmap.ko
subsystems                  generic monitor pipe vale
kernel sources              /home/downloads/linux-bananapi
requested drivers           veth.c

Contents of the drivers.mak file:

  Note: only drivers for which both the <driver>-src and the
  <driver>-patch variable are set may be used in native mode (assuming
  we can actually patch the sources). Other NICs will be accessed using
  the generic driver, at reduced performance.
###### 

#  configure generated values          #
###### 

veth.c-src := /home/downloads/linux-bananapi/drivers/net/veth.c
veth.c-patch := patches/diff--veth.c--20620--30900
veth.c-dst := veth.c

<b> make SRC=/home/downloads/linux-bananapi KSRC=/usr/src/linux-headers-3.4.104-bananian apps </b>
make -C build-apps SRCDIR=/home/downloads/netmap/LINUX/.. CC="cc" LD="ld"
make[1]: Entering directory `/home/downloads/netmap/LINUX/build-apps'
cc -O2 -pipe -Werror -Wall -Wunused-function -I /home/downloads/netmap/LINUX/../sys  -Wextra -DNO_PCAP   -c -o pkt-gen.o /home/downloads/netmap/LINUX/../examples/pkt-gen.c
cc   pkt-gen.o  -lpthread -lrt   -o pkt-gen
cc -O2 -pipe -Werror -Wall -Wunused-function -I /home/downloads/netmap/LINUX/../sys  -Wextra -DNO_PCAP -DBUSYWAIT -c /home/downloads/netmap/LINUX/../examples/pkt-gen.c -o pkt-gen-b.o
cc   pkt-gen-b.o  -lpthread -lrt         -o pkt-gen-b
cc -O2 -pipe -Werror -Wall -Wunused-function -I /home/downloads/netmap/LINUX/../sys  -Wextra -DNO_PCAP   -c -o bridge.o /home/downloads/netmap/LINUX/../examples/bridge.c
cc   bridge.o  -lpthread -lrt    -o bridge
cc -O2 -pipe -Werror -Wall -Wunused-function -I /home/downloads/netmap/LINUX/../sys  -Wextra -DNO_PCAP    /home/downloads/netmap/LINUX/../examples/testmmap.c  -lpthread -lrt    -o testmmap
/home/downloads/netmap/LINUX/../examples/testmmap.c: In function ‘do_if’:
/home/downloads/netmap/LINUX/../examples/testmmap.c:540:3: error: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘ssize_t’ [-Werror=format]
cc1: all warnings being treated as errors
make[1]: *** [testmmap] Error 1
make[1]: Leaving directory`/home/downloads/netmap/LINUX/build-apps'
make: **\* [apps] Error 2

<b> make SRC=/home/downloads/linux-bananapi KSRC=/usr/src/linux-headers-3.4.104-bananian </b>
make -C /usr/src/linux-headers-3.4.104-bananian M=/home/downloads/netmap/LINUX EXTRA_CFLAGS='-I/home/downloads/netmap/LINUX -I/home/downloads/netmap/LINUX -I/home/downloads/netmap/LINUX/../sys -I/home/downloads/netmap/LINUX/../sys/dev -DCONFIG_NETMAP -Wno-unused-but-set-variable -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE'  modules CONFIG_NETMAP=m CONFIG_VETH=m  O_DRIVERS="veth.o" \
                NETMAP_DRIVER_SUFFIX=
make[1]: Entering directory `/usr/src/linux-headers-3.4.104-bananian'
  CC [M]  /home/downloads/netmap/LINUX/netmap_mem2.o
  CC [M]  /home/downloads/netmap/LINUX/netmap_mbq.o
  CC [M]  /home/downloads/netmap/LINUX/netmap_vale.o
  CC [M]  /home/downloads/netmap/LINUX/netmap_offloadings.o
  CC [M]  /home/downloads/netmap/LINUX/netmap_pipe.o
  CC [M]  /home/downloads/netmap/LINUX/netmap_monitor.o
  CC [M]  /home/downloads/netmap/LINUX/netmap_generic.o
  CC [M]  /home/downloads/netmap/LINUX/netmap_common.o
  CC [M]  /home/downloads/netmap/LINUX/netmap_linux.o
  LD [M]  /home/downloads/netmap/LINUX/netmap.o
  CC [M]  /home/downloads/netmap/LINUX/veth.o
  Building modules, stage 2.
  MODPOST 2 modules
  CC      /home/downloads/netmap/LINUX/netmap.mod.o
  LD [M]  /home/downloads/netmap/LINUX/netmap.ko
  CC      /home/downloads/netmap/LINUX/veth.mod.o
  LD [M]  /home/downloads/netmap/LINUX/veth.ko
make[1]: Leaving directory`/usr/src/linux-headers-3.4.104-bananian'

**Comment by MappaM** [comment] 2015-08-24 15:19
Netmap itself seems to compile fine, there is only an error in bulding the eample apps. You should be able to do insmod netmap.ko to load netmap.

The problem is more that your driver is not natively supported by Netmap. RTL8211E in the banana? Netmap has native support for only a few drivers and not that particulary one. However it should supports non-native drivers through the normal kernel stack, but I never used that.

**Comment by sasukeskapa** [comment] 2015-08-25 13:03
We are testing it with OVS right now and it perform exactly as it did before and we suspect that OVS simply doesn't use netmap. Is there a way to compile the example apps to test if it works? Or is there a way to check if netmap is working or just runs in the background?

**Comment by vmaffione** [comment] 2015-08-25 16:58
At the best of my knowledge, netmap integration with OVS is not ready/available. If you want to play with netmap using VALE switch, you can just compile the example applications (the examples directory) and then:
````
# insmod netmap.ko
# ./pkt-gen -f rx -i vale0:1 # on the first terminal
# ./pkt-gen -f tx -i vale0:2 # on another terminal

In this example you have and application sending through a port of a VALE switch (vale0) and another application reading from another port of the same switch.
A similar experiment can be carried out with pipes. Refer to the man page for full explanations.

You can attach an existing (physical or virtual) network interface to a vale bridge.
Or simply send (receive) directly from an existing interface, e.g.

# ./pkt-gen -f tx -i eth3

If your 10Gbit (or more) network adapter is not natively supported by netmap, you will have a performance penality of 5-10x in the worst case (64 bytes ethernet frames).

**Comment by vmaffione** [comment] 2016-12-10 17:33
In any case,you should try again with the new build system. Just ./configure and make in the root directory

**Comment by vmaffione** [comment] 2016-12-26 13:34
Closing,this issue does nott reflect current code. Please open another one if needed

**Closed by vmaffione** 2016-12-26 13:34 UTC
