### ISSUE TITLE
NIC <-> Host Inspection/transform

### ISSUE THREAD

**Issue by j-t-d** [luigirizzo/netmap#608] opened 2019-04-12 22:11 UTC
Hi, I was playing with netmap to see if it could intercept and (eventually) transform packets pre-kernel using the host rings.

I've come up with this using NS_FORWARD: https://gist.github.com/j-t-d/da34a5cbc99a2493c34f4c8f5791a153

However, the issue I'm running into is that, even though I'm polling on the 'host rx' side, it never wakes up. Packets are still going through the host -> nic side.

I'm sure I'm missing something, but I can't spot it.

**Comment by vmaffione** [comment] 2019-04-13 13:10
When the kernel tries to transmit a packet on TX ring K, netmap steals it (and put it into the host RX ring K % num_host_rx_rings) only if that TX ring K is in netmap mode. In your program, only RX rings and host RX rings are opened in netmap mode, so netmap does not intercept kernel transmission, and nothing ends up into the host RX rings.

Try to move that `nmport_close(foo)` together with `close_rings()`.

Btw, that global variable `packets` can be a performance bottleneck at very high rate, so you should probably use per-thread counters.

**Comment by j-t-d** [comment] 2019-04-13 17:51
> 
> 
> When the kernel tries to transmit a packet on TX ring `K`, netmap steals it (and puts it into the host RX ring `K % num_host_rx_rings`) only if that TX ring `K` is in netmap mode. In your program, only RX rings and host RX rings are opened in netmap mode, so netmap does not intercept kernel transmission, and nothing ends up into the host RX rings.
> 
> Try to move that `nmport_close(foo)` together with `close_rings()`.
> 

Ah ok. So the initial open I was using to figure out how many nic rings there was and to open similar number of host rings.  I can just figure that out using ethtool ioctl. 

So if I change the first open to host-rings=<num nic rings>, and leave it open, it won't interfere with the individual rings that I open per thread?

> Btw, that global variable `packets` can be a performance bottleneck at very high rate, so you should probably use per-thread counters.

It's mostly just there so I can see that things are happening. But good point, thanks.

**Comment by vmaffione** [comment] 2019-04-14 07:48
You can use the `PORT_INFO_GET` command to get information:
https://github.com/luigirizzo/netmap/blob/master/utils/ctrl-api-test.c#L178
This gives you more information than ethtool, and it is also portable to FreeBSD.

Netmap allows you to open each ring (hw or host) how many times you wish. It's up to you to serialize access to each ring. If you open a ring and do not use it, that's harmless.

Yes, once you figure out the number of RX rings, you can do a `nmport_open()` that opens everything, specifying the desired number of host rings.

**Comment by j-t-d** [comment] 2019-04-15 19:42
Awesome. I've update the gist with these changes. I'm now getting packets both directions.

However, it seems that NS_FORWARD isn't working correctly. Should I instead be doing "zero-copy forwarding" (as it says in the manpage), between host rings and nic rings?

**Comment by vmaffione** [comment] 2019-04-15 20:31
Yes, application normally zero-copy forward between the host rings and the nic rings, rather than using NS_FORWARD.
NS_FORWARD is an old feature that is not really being used. We don't even have examples using NS_FORWARD.
In netmap you can zero-copy forward between two rings by swapping the slot contents. You can look at the `bridge` program to see how to do that.

**Comment by j-t-d** [comment] 2019-04-15 22:30
Ok. I've updated the gist yet again. This is working for me.

Do you have any additional suggestions (outside of fixing my debug stat)? I do see iperf3 showing a lot of retries in either direction. I also can't seem to get the packet rate over 1Mpps even though I'm not cpu bound.

**Comment by vmaffione** [comment] 2019-04-18 12:37
I think your code normally uses two syscalls() for cycle, a `poll()` on the RX port, and an `ioctl()` on the TX port. You could use a single `poll()` to do both. You could just look at the `bridge` example and use the same forwarding scheme.

**Comment by vmaffione** [comment] 2019-04-18 12:39
Also, keep in mind that host rings are quite slow, and there is nothing that can be done about that, by design. You can read more about this in #220, or in other threads that discuss the same thing.

**Comment by j-t-d** [comment] 2019-04-24 21:02
I made the changes you suggested. (Just spent the last week getting the mlx5 patch working on the latest linux kernel). It seems egress traffic is pretty quick (about 20gbit/s @ 1500 byte packets, from host ring -> nic -> other nic), but ingress is considerably slower (same setup, but 6gbit/s).

Any tuning suggestions to get the ingress traffic to be on par with the egress traffic?

**Comment by vmaffione** [comment] 2019-04-26 14:29
How many host RX and TX rings are you using?

**Comment by j-t-d** [comment] 2019-04-26 16:46
I'm using 8, to match what I have the NIC configured to. I've dropped the NIC from 32 -> 8 because of Netmap complaining about memory allocations, and I haven't had time to tune those yet.

I have this patch:
https://gist.github.com/j-t-d/57d43c8251d02e65f97c2f2e38bc75bf

Which I've taken from the original mellanox 4.5 patch and updated to work with 5.0 of the linux kernel. There's potentially an issue with it, as under heavy UDP traffic, I call out to poll with POLLIN and never get notified.

**Comment by j-t-d** [comment] 2019-04-26 18:01
Just to follow up, I did some testing on a i40e 10gbit/s card I have, and I can hit 10gbit full duplex there. So I'm guessing that the mlx5 patch I have has an issue of some sort? I pretty much just blindly patched it by comparing the older patched version to the newer kernel.

**Comment by vmaffione** [comment] 2019-04-27 14:26
Yes, it can be that the mlx5 patch has problems for ingress traffic. As far as I understand, the people that contributed the mlx5 patch mainly use it to transmit (for channel broadcast applications).

**Comment by j-t-d** [comment] 2019-05-09 23:47
I'm getting this pretty often, and performance sort of degrades over time:

[274844.670505] 206.150059 [1692] nm_txsync_prologue        eth0 TX43: fail 'cur > kring->rtail && cur < head' h 324 c 323 t 295 rh 296 rc 296 rt 295 hc 296 ht 295
[274844.670507] 206.150064 [1787] netmap_ring_reinit        called for eth0 TX43
[274845.254325] 206.733881 [1692] nm_txsync_prologue        eth0 TX46: fail 'cur > kring->rtail && cur < head' h 382 c 381 t 287 rh 288 rc 288 rt 287 hc 288 ht 287
[274845.254327] 206.733886 [1787] netmap_ring_reinit        called for eth0 TX46
[274845.434271] 206.913827 [1692] nm_txsync_prologue        eth0 TX62: fail 'cur > kring->rtail && cur < head' h 468 c 467 t 455 rh 456 rc 456 rt 455 hc 456 ht 455
[274845.434274] 206.913833 [1787] netmap_ring_reinit        called for eth0 TX62
[274845.593906] 207.073461 [1692] nm_txsync_prologue        eth0 TX38: fail 'cur > kring->rtail && cur < head' h 188 c 187 t 143 rh 144 rc 144 rt 143 hc 144 ht 143
[274845.593908] 207.073467 [1787] netmap_ring_reinit        called for eth0 TX38

Looking at #220 I noticed that this is caused by data races.

Do I need to initialize the TX and RX rings to have separate descriptors for both host and nic? Right now I do the NIC rings and the the Host rings, and split them apart (ie: host rx + nic tx). I do poll read on one fd, and poll write on the other fd).

**Comment by giuseppelettieri** [comment] 2019-05-10 08:06
I am not sure I understand your fd setup, so this may not be relevant: please be aware that a netmap poll read on an fd will also start an automatic tx sync on the fd by default. To disable this feature you need to set the ```NR_NO_TX_POLL``` flag in the ```nr_flags``` field of the ```nmreq_register``` structure when you open the fd. (This is assuming that you are using the new ```NIOCCTRL``` API, otherwise you need to use the flag by the same name in the legacy ```nmreq``` structure).

**Comment by j-t-d** [comment] 2019-05-10 17:50
I have an example of what I'm trying to do at this gist (posted above): https://gist.github.com/j-t-d/da34a5cbc99a2493c34f4c8f5791a153

**Comment by giuseppelettieri** [comment] 2019-05-22 09:41
Hi @j-t-d, I have finally found the time to take a look at your code. You are indeed putting in netmap mode also the TX rings of the NIC, which is not needed in your case. This will make the kernel unable to send through the NIC without help from your app (I don't know if this is intended) and will cause netmap to run useless TX syncs on the TX rings (even if you just ```POLLIN``` on the NIC rings, since the ```NR_NO_TX_POLL``` flag has not ben set). All this, however, should not cause the problems you are seeing, if nobody is touching the NIC TX rings, so there may be a bug somewhere that I am going to investigate.

In the meantime, you may try to open just the rings that you need: add the ```/R``` flag to the port name when you open the NIC rings and the ```/T``` flag when you open the host rings. There is then no need to set the ```NR_NO_TX_POLL``` on the NIC rings, since you don't have any NIC TX ring open anymore. E.g. ```enp0s0f1-1/R@conf:host-rings=8``` and ```enp0s0f1^1/T@conf:host-rings=8```.

**Comment by j-t-d** [comment] 2019-05-22 17:41
Hi Guiseppe.

Perfect, that's exactly what we did and it removed the issue. It seems to be working ok now.  We're doing inline transport ipsec (aes-128-gcm) with this method, transparent to the underlying kernel stack.

**Comment by giuseppelettieri** [comment] 2019-05-23 07:26
Perfect, I am closing this then.

**Closed by giuseppelettieri** 2019-05-23 07:26 UTC
Labels: question
