### ISSUE TITLE
Kernel panic on free NR_REG_SW after NR_REG_ONE_NIC

### ISSUE THREAD

**Issue by junjunk** [luigirizzo/netmap#144] opened 2016-02-19 09:39 UTC
If NR_REG_SW ring is used with NR_REG_ONE_NIC and created the last, then if we trying to free NR_REG_SW after NR_REG_ONE_NIC we get kernel panic. 
Workaround - free NR_REG_SW before NR_REG_ONE_NIC ring.
I think that this behavior is not good and is not described

**Comment by giuseppelettieri** [comment] 2016-02-19 11:34
may you provide some example code to reproduce the panic?

**Comment by junjunk** [comment] 2016-02-20 08:32
I've found such behavior using suricata-ids version 3.0.
Init code:
```
#define IFNAME "eth0"
int fd = open("/dev/netmap", O_RDWR);
struct nmreq nm_req;
memset(&nm_req, 0, sizeof(nm_req));
strlcpy(nm_req.nr_name, IFNAME, sizeof(nm_req.nr_name));
nm_req.nr_version = NETMAP_API;
   if (ioctl(fd, NIOCGINFO, &nm_req) != 0) {
        if (verbose) {
            SCLogError(SC_ERR_NETMAP_CREATE,
                       "Couldn't query netmap for %s, error %s",
                       ifname, strerror(errno));
        }
        goto error_fd;
    };
int rings_cnt = max(nm_req.nr_rx_rings, nm_req.nr_tx_rings);
int *fd_rings = malloc(sizeof(int)*(rings_cnt+1));
for (int i = 0; i <= rings_cnt; i++) {
   fd_rings[i] = open("/dev/netmap", O_RDWR);
       if (i < rings_cnt) {
            nm_req.nr_flags = NR_REG_ONE_NIC;
            nm_req.nr_ringid = i | NETMAP_NO_TX_POLL;
        } else {
            nm_req.nr_flags = NR_REG_SW;
            nm_req.nr_ringid = NETMAP_NO_TX_POLL;
        }
        if (ioctl(fd[i], NIOCREGIF, &nm_req) != 0) {
            SCLogError(SC_ERR_NETMAP_CREATE,
                       "Couldn't register %s (ring %d) with netmap: %s",
                       IFNAME, i, strerror(errno));
            break;
        }
}
```
and then close code 
```
              for (int i = 0; i <= rings_cnt; i++) {
                    close(fd_rings[i]);
                }
```
assuming we know rings_cnt and fd_rings values
This is a simple sample, in the real software it is more complex  but with the same meaning

**Comment by junjunk** [comment] 2016-02-20 08:52
The same code works well with netmap git version from March 2015

**Comment by aspotapov** [comment] 2016-03-28 21:54
Reproduced with sample utility /examples/bridge.c. I ran it like this
`./bridge -i netmap:eth0^ -i netmap:eth0`
Ctrl+C make my system hang, but
`./bridge -i netmap:eth0 -i netmap:eth0^`
works normal. 

OS Debian 8.3 
`$ uname -a`
`Linux jessie 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux`
netmap built from branch "master" with option "--no-drivers"

**Comment by flybeyond** [comment] 2016-03-31 09:40
met the same issue in latest commit

**Comment by vmaffione** [comment] 2016-03-31 10:39
What kind of interface is eth0, exactly? I assume you are not using patched
drivers (--no-drivers)


2016-03-31 11:40 GMT+02:00 flybeyond <notifications@github.com>:

> met the same issue in latest commit
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/144#issuecomment-203854389>
>



-- 
Vincenzo Maffione

**Comment by vmaffione** [comment] 2016-12-20 11:05
@flybeyond @aspotapov @gureedo @junjunk 
I tried to reproduce this error (in particular using the bridge program as @aspotapov is suggesting), but with no success, so maybe the error is not there anymore.

If you still see the bug (with current code), can you please share the details of the distribution you are using?

**Comment by vmaffione** [comment] 2017-04-25 21:10
Cannot reproduce the error anymore, closing

**Closed by vmaffione** 2017-04-25 21:10 UTC
Labels: bug
