### ISSUE TITLE
Packet Not Being Dispatched from TX ring

### ISSUE THREAD

**Issue by Alessandro1011** [luigirizzo/netmap#297] opened 2017-04-15 10:28 UTC
I have done a sample application that uses the below code. 
Basically i am sending from one machine to another which are connected back to back.

In free BSD 10.2 Stable the packets are being sent but with a big delay and on free BSD 11 stable  the packets are being copied to the ring but are never dispatched. note that the "synch" for ioctl never fails 

Could you please indicate what i can do to solve this issue please.

Code being used to send packets.
    nm_inject(adsp_ring->adsc_nm_desc, (void *)abyp_data, (size_t)ump_data_size);
    int im_ret = ioctl(adsp_ring->adsc_nm_desc->fd, NIOCTXSYNC, NULL);
    if (im_ret < 0)
        printf("Error");

Thanks 

Kind regard 
Sandro :)

**Comment by vmaffione** [comment] 2017-04-15 10:43
Does nm_inject return the packet size? Or does it fail returning 0?
How did you nm_open?
Which network interface are you using?

**Comment by Alessandro1011** [comment] 2017-04-15 11:00
nm_inject: 
nm_inject returned:    598
Packet Size:                598
NIOCTXSYNC ioctl returned: 0

nm_open: This is being done using the following code: 
        sprintf(ads_ring->chrc_name, "netmap:%s-%d", ds_nic.chrc_name, um);
        ads_ring->adsc_nm_desc = nm_open(ads_ring->chrc_name, 0, 0, 0);
Network interfaces being used: FREEBSD 10 - X540 Network Cards
                                                   FREEBSD 11 - XL710 Network Cards

**Comment by vmaffione** [comment] 2017-04-15 11:10
Which delays are you seeing?
Have you tried to set syscl dev.netmap.admode=2 ?

**Comment by Alessandro1011** [comment] 2017-04-15 11:17
when doing test on freebsd 10 on sending the packets are taking long to be dispatched from the network card. on the other hand on freebsd 11 packets are not being dispatched at all.

no currently i am using admode set to 0

**Comment by vmaffione** [comment] 2017-04-15 13:45
Admode takes effect on a nic after all netmap applications using that nic have terminated. It's just a sysctl. Stop your applications, change admode and retry.

**Comment by Alessandro1011** [comment] 2017-04-15 14:01
tried admode=2 but still with same problem.

**Comment by vmaffione** [comment] 2017-04-15 15:05
You can try downloading netmap source from github and recompile your kernel with updated code. If it still doesn't work it means that the problem is in your application

**Comment by vmaffione** [comment] 2017-04-25 21:05
any news?

**Comment by vmaffione** [comment] 2017-12-06 11:11
Fixed by #392

**Closed by vmaffione** 2017-12-06 11:11 UTC
