### ISSUE TITLE
Memory Leak - Linux

### ISSUE THREAD

**Issue by Fr3DBr** [luigirizzo/netmap#213] opened 2016-08-31 01:53 UTC
Hi, guys.

I'm using the following code: 

https://github.com/jibi/nm-single-rx-queue/blob/master/main.c

What happens is that when I open "two processes" or more, basically one process per rx queue, then misteriously a massive memory leak happens. (Linux / CentOS 7).

Would you know why is this ?

Thanks. :+1: 
## 

I think, this happens because I'm sharing the same descriptor in the different processes right ? (Via nm_open).
## 

Actually, I've tried using separated nm_open calls (one per queue) and adjusting nm_desc parameters this way:

```
            uint64_t nmd_flags = 0;
            nmd.req.nr_flags &= ~NR_REG_MASK;
            nmd.req.nr_flags |= NR_REG_ONE_NIC;
            nmd.req.nr_ringid = ring_id;
            pnmd = nm_open("netmap:ens1f0", NULL, nmd_flags | NM_OPEN_IFNAME | NM_OPEN_NO_MMAP, &nmd);
            if ( pnmd == NULL ) {
                    printf("Interface Opening Error: %s\n", strerror(errno));
                    return NULL;
            }
```

But the memory leak still persists, and it happens after the packets are forwarded to the host stack, is I'm missing anything here, to avoid this behavior ?

**Comment by Fr3DBr** [comment] 2016-08-31 14:40
I think, this happens because I'm sharing the same descriptor in the different processes right ?

**Comment by Fr3DBr** [comment] 2016-08-31 18:24
Actually, I've tried using separated nm_open calls (one per queue) and adjusting nm_desc parameters this way:

                uint64_t nmd_flags = 0;
                nmd.req.nr_flags &= ~NR_REG_MASK;
                nmd.req.nr_flags |= NR_REG_ONE_NIC;
                nmd.req.nr_ringid = ring_id;
                pnmd = nm_open("netmap:ens1f0", NULL, nmd_flags | NM_OPEN_IFNAME | NM_OPEN_NO_MMAP, &nmd);
                if ( pnmd == NULL ) {
                        printf("Interface Opening Error: %s\n", strerror(errno));
                        return NULL;
                }

But the memory leak still persists, and it happens after the packets are forwarded to the host stack, is I'm missing anything here, to avoid this behavior ?

**Comment by vmaffione** [comment] 2016-08-31 18:55
How do you detect the memory leak?
Can you post the simplest steps that you can follow to reproduce the issue?

**Comment by Fr3DBr** [comment] 2016-08-31 18:57
Just checking "top", the memory usage increases up to 100%.

1) Load netmap module (insmod netmap.ko)
2) Forward 100% of packets to the host stack (requires commenting a few lines in the code).
3) Starts 2 or more processes, specifying multiple rings (0, 1, 2, 3)
4) Send 14 Mpps towards the machine processing the packets.

Then the memory usage will hit 100% and the system will crash without memory.

**Comment by Fr3DBr** [comment] 2016-08-31 20:31
It worth to mention, that even if you kill the process after the memory leak has been caused, the memory will not be released back to the system.

**Comment by Fr3DBr** [comment] 2016-09-01 00:33
Ok, this also happens with pkt-gen.c, same problem. The only change necessary to be done there is:

receive_packets add the following lines:

                /* Forward to the host stack */
                ring->flags |= NR_FORWARD;
                slot->flags |= NS_FORWARD;

after:

                if (dump)
                        dump_payload(p, slot->len, ring, cur);

So the packets will be forwarded to host stack in RX mode, also it is necessary to set number of CPUs to 4 and Threads to 4.

Not sure why is that, but I think this is a bug. :)

**Comment by Fr3DBr** [comment] 2016-09-01 00:37
Oh, and I'm not using patched drivers, I've compiled netmap without drivers. (I think this is an important information too).

**Comment by Fr3DBr** [comment] 2016-09-01 00:39
Top results after a few seconds test run:

--
KiB Mem : 32691068 total, 11977616 free, 13713480 used,  6999972 buff/cache
--

**Comment by vmaffione** [comment] 2016-09-01 08:22
Thanks for the detailed report, this is clearly a bug related to the NS_FORWARD flag. It went unnoticed because the NS_FORWARD is a rather ancient feature that I don't think is commonly used (at least I never used that).

**Comment by Fr3DBr** [comment] 2016-09-01 11:08
Yeah, I am planning to use this, in my application but unfortunately, I've got this surprise. :P

**Comment by Fr3DBr** [comment] 2016-09-01 14:17
Ah, Just another observation, the NR_FORWARD and NS_FORWARD flags aren't working in FreeBSD, basically the packets aren't forwarded to the host stack. (There is no memory leak, but also, there's no effect).

**Comment by vmaffione** [comment] 2016-09-02 06:55
Yes, exactly, you can do the same in that way for the moment

**Comment by Fr3DBr** [comment] 2016-09-03 13:57
I think this "bug" is directly related with this, look:

https://github.com/luigirizzo/netmap/issues/220 <-

**Comment by vmaffione** [comment] 2017-01-05 09:59
Hi,
  I've found a memory leak related to NS_FORWARD (and fixed it, see 9438c3cbcc454b05433c8c26a7cb1a6154fff1a7).

From your description, it seems that it matches your report. Can you please check if the problem disappeared with the current master?

**Comment by vmaffione** [comment] 2017-01-05 10:03
By the way, your code here https://github.com/jibi/nm-single-rx-queue/blob/master/main.c has a small problem: you need to set in NR_FOWARD in ring->flag just once and before the loop.

**Comment by vmaffione** [comment] 2017-01-29 18:24
This should be fixed now. If the problem is still there in your setup please reopen

**Closed by vmaffione** 2017-01-29 18:24 UTC
Labels: bug
