### ISSUE TITLE
Recent change in lb code has broken Freebsd 11.1 p1 support

### ISSUE THREAD

**Issue by m1357** [luigirizzo/netmap#379] opened 2017-10-11 21:31 UTC
Using a git pull from ~ 1 month ago everything works as expected. I was building out a new node and did a fresh pull and get the following error on startup : 

/lb -i ix0 -p 20
386.864375 main [600] interface is ix0
387.202400 main [714] successfully opened netmap:ix0 (tx rings: 2048)
387.202418 main [784] opening pipe named netmap:ix0{0/xT@1
387.202635 nm_mmap [987] do not mmap, inherit from parent
387.202642 main [799] successfully opened pipe #1 netmap:ix0{0/xT@1 (tx slots: 2048)
387.202644 main [803] zerocopy enabled
387.202646 main [784] opening pipe named netmap:ix0{1/xT@1
387.202727 nm_open [948] NIOCREGIF failed: Device busy netmap:ix0{1/xT@1
387.202731 main [789] cannot open netmap:ix0{1/xT@1
387.202741 free_buffers [374] added 0 buffers to netmap free list

Not sure what other information I can provide on this but let me know and I will happily contribute. I can verify this is happening on ix and ixl driver.

**Comment by giuseppelettieri** [comment] 2017-10-12 09:38
Hi @m1357, this should be fixed in commit d9a02966, which is the current master pushed the day before yesterday. Are you already using that? Please note that, to properly rebuild 'lb' after the pull, you need to 'make clean; make'.

**Comment by vmaffione** [comment] 2017-11-02 11:01
Unconfirmed, please open if the problem is still there.

**Closed by vmaffione** 2017-11-02 11:01 UTC
Labels: bug
