### ISSUE TITLE
BUG: unable to handle kernel NULL pointer dereference when trying to open disabled interface

### ISSUE THREAD

**Issue by pavel-odintsov** [luigirizzo/netmap#176] opened 2016-05-11 12:56 UTC
Hello!

I have bug with strong reproducer. This bug will definitely kill Linux kernel if somebody tried to open in netmap mode some disabled device. 

Reproduce list if following:
```bash
1) Start server with netmap enabled ixgbe driver.
2) Run netmap application
3) Stop netmap application 
4) Switch down interface: ifconfig eth5 down
5) Run pkt-gen: ./pkt-gen -i eth5 -f rx on disabled interface.
6) Switch on interface: ifconfig eth5 up
7) Got killed server with panic:
```

```bash
[ 1521.404035] init: dps main process (1848) terminated with status 1
[ 1521.461046] ixgbe 0000:1b:00.0 eth5: detected SFP+: 6
[ 1521.604042] ixgbe 0000:1b:00.0 eth5: NIC Link is Up 10 Gbps, Flow Control: RX/TX
[ 1521.690168] 062.442814 [2031] netmap_do_regif           lut ffffc9000449c000 bufs 163840 size 2048
[ 1521.782208] 062.534855 [ 471] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[ 1521.784044] 062.536692 [ 471] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[ 1521.786152] 062.538789 [ 471] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[ 1521.788020] 062.540670 [ 471] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[ 1521.956051] ixgbe 0000:1b:00.0 eth5: detected SFP+: 6
[ 1522.196155] ixgbe 0000:1b:00.0 eth5: NIC Link is Up 10 Gbps, Flow Control: RX/TX
[ 8275.182165] init: dps main process (1996) terminated with status 1
[ 8275.244053] ixgbe 0000:1b:00.0 eth5: detected SFP+: 6
[ 8275.384039] ixgbe 0000:1b:00.0 eth5: NIC Link is Up 10 Gbps, Flow Control: RX/TX
[ 8429.360430] 970.113076 [2031] netmap_do_regif           lut ffffc9000449c000 bufs 163840 size 2048
[ 8429.450060] 970.202693 [ 471] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[ 8429.452034] 970.204682 [ 471] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[ 8429.453727] 970.206374 [ 471] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[ 8429.455843] 970.208490 [ 471] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[ 8429.626605] ixgbe 0000:1b:00.0 eth5: detected SFP+: 6
[ 8429.760113] ixgbe 0000:1b:00.0 eth5: NIC Link is Up 10 Gbps, Flow Control: RX/TX
[ 8481.846199] init: dps main process (2260) terminated with status 1
[ 8481.916319] ixgbe 0000:1b:00.0 eth5: detected SFP+: 6
[ 8482.048016] ixgbe 0000:1b:00.0 eth5: NIC Link is Up 10 Gbps, Flow Control: RX/TX
[ 8482.140467] 022.893114 [2031] netmap_do_regif           lut ffffc9000449c000 bufs 163840 size 2048
[ 8482.230200] 022.982840 [ 471] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[ 8482.231988] 022.984634 [ 471] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[ 8482.233137] 022.985773 [ 471] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[ 8482.235216] 022.987865 [ 471] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[ 8482.408126] ixgbe 0000:1b:00.0 eth5: detected SFP+: 6
[ 8482.640067] ixgbe 0000:1b:00.0 eth5: NIC Link is Up 10 Gbps, Flow Control: RX/TX
[ 8540.263784] init: dps main process (2437) terminated with status 1
[ 8540.330773] ixgbe 0000:1b:00.0 eth5: detected SFP+: 6
[ 8540.464034] ixgbe 0000:1b:00.0 eth5: NIC Link is Up 10 Gbps, Flow Control: RX/TX
[ 8540.549260] 081.301904 [2031] netmap_do_regif           lut ffffc9000449c000 bufs 163840 size 2048
[ 8540.634880] 081.387527 [ 471] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[ 8540.636096] 081.388745 [ 471] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[ 8540.638567] 081.391215 [ 471] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[ 8540.641265] 081.393913 [ 471] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
[ 8540.808835] ixgbe 0000:1b:00.0 eth5: detected SFP+: 6
[ 8540.948044] ixgbe 0000:1b:00.0 eth5: NIC Link is Up 10 Gbps, Flow Control: RX/TX
[ 8776.270564] init: dps main process (2534) terminated with status 1
[ 8776.332774] ixgbe 0000:1b:00.0 eth5: detected SFP+: 6
[ 8776.472036] ixgbe 0000:1b:00.0 eth5: NIC Link is Up 10 Gbps, Flow Control: RX/TX
[ 8782.470874] ixgbe 0000:1b:00.0: removed PHC on eth5
[ 8786.939922] 327.692567 [2031] netmap_do_regif           lut ffffc9000449c000 bufs 163840 size 2048
[ 9282.130968] init: dps main process (2683) terminated with status 1
[ 9647.746292] init: tera_tsdb main process (2272) killed by TERM signal
[ 9757.432012] BUG: unable to handle kernel NULL pointer dereference at 0000000000000024
[ 9757.432832] IP: [<ffffffffc00ea902>] netmap_reset+0xd2/0x1b0 [netmap]
[ 9757.433535] PGD 4a6074067 PUD 49a237067 PMD 0
[ 9757.434234] Oops: 0000 [#1] SMP
[ 9757.434933] Modules linked in: ppdev vmw_balloon coretemp crct10dif_pclmul crc32_pclmul aesni_intel aes_x86_64 lrw gf128mul glue_helper ablk_helper cryptd joydev input_leds serio_raw vmwgfx ttm drm_kms_helper drm vmw_vmci i2c_piix4 shpchp 8250_fintek parport_pc mac_hid lp parport mptspi ixgbe(OE) netmap(OE) dca vxlan ip6_udp_tunnel udp_tunnel ptp psmouse pps_core mptscsih mptbase vmxnet3 scsi_transport_spi pata_acpi floppy
[ 9757.438665] CPU: 1 PID: 2904 Comm: dps Tainted: G           OE   4.2.0-36-generic #41~14.04.1-Ubuntu
[ 9757.440245] Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 09/30/2014
[ 9757.441814] task: ffff8800ba4e0dc0 ti: ffff880498944000 task.ti: ffff880498944000
[ 9757.442617] RIP: 0010:[<ffffffffc00ea902>]  [<ffffffffc00ea902>] netmap_reset+0xd2/0x1b0 [netmap]
[ 9757.443466] RSP: 0018:ffff880498947b28  EFLAGS: 00010246
[ 9757.444336] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000000
[ 9757.445218] RDX: 0000000000000000 RSI: 0000000000000001 RDI: ffff8804a5659800
[ 9757.446082] RBP: ffff880498947ba8 R08: ffff880498944000 R09: 0000000000000000
[ 9757.446926] R10: 0000000000000001 R11: 0000000000005a07 R12: ffff8804a5659800
[ 9757.447789] R13: 0000000000006028 R14: 0000000000000000 R15: 0000000000000000
[ 9757.448673] FS:  00007f16267fc700(0000) GS:ffff8804bfc80000(0000) knlGS:0000000000000000
[ 9757.449568] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[ 9757.450446] CR2: 0000000000000024 CR3: 000000049ca4f000 CR4: 00000000000406e0
[ 9757.451395] Stack:
[ 9757.452262]  00000b5800000000 ffffffff817c2a16 74696e0000737064 0000000000000000
[ 9757.453176]  0000000000000000 00000000cad2206
```

**Comment by vmaffione** [comment] 2016-05-11 15:40
Just tried the steps twice, using 

````
# pkt-gen -i ethX -f rx
````

as a netmap application. But I cannot see the crash, and things keep working fine to me.

**Comment by pavel-odintsov** [comment] 2016-05-11 15:44
Thanks for answer! I've reproduced this bug on two different machines with 4.2 kernel. But we are using patched ixgbe from sourceforge.net distributed here: https://github.com/pavel-odintsov/ixgbe-linux-netmap 

I've checked it with ixgbe-4.1.5 and ixgbe-4.3.15 drivers.  And both drivers produce kernel panic.

**Comment by vmaffione** [comment] 2016-05-11 15:48
I'm using the linux 4.5, and the kernel sources distributed by Archlinux (which are basically the same as the kernel.org ones).

**Comment by pavel-odintsov** [comment] 2016-05-11 15:50
I have kernel kdump image. Could it be useful for you for investigation?

**Comment by vmaffione** [comment] 2016-05-11 16:31
Thanks, but I don't think so. Have you tried to use the drivers from kernel.org?

**Comment by pavel-odintsov** [comment] 2016-05-11 17:06
Hello

I'm using RSS for load distribution but vanilla driver hasn't this
option... But I could try to reproduce this bug.

If it important first application uses multiple threads for traffic capture.

On Wednesday, 11 May 2016, Vincenzo Maffione <notifications@github.com>
wrote:

> Thanks, but I don't think so. Have you tried to use the drivers from
> kernel.org?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/176#issuecomment-218514738>
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by potahov** [comment] 2016-05-11 17:57
This (or similar) kernel panic also happens when you try to bring down the interface when it is still opened in netmap mode.

**Comment by pavel-odintsov** [comment] 2016-05-11 18:49
Alexey, thanks for contribution! I'll try to repeat this case too. Could
you try to reproduce original issue?

On Wednesday, 11 May 2016, Alexey Potakhov <notifications@github.com> wrote:

> This (or similar) kernel panic also happens when you try to bring down the
> interface when it is still opened in netmap mode.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/176#issuecomment-218539008>
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by potahov** [comment] 2016-05-11 19:17
I couldn't reproduce it your way, it doesn't panic for me when I bring interface up.

**Comment by vmaffione** [comment] 2016-05-23 19:11
It seems that using netmap code in this repository, the bug cannot be reproduced, so closing this.

**Closed by vmaffione** 2016-05-23 19:11 UTC
