### ISSUE TITLE
Fluctuating utilization in 10G Intel ixgbe driver

### ISSUE THREAD

**Issue by sibirchakraborty** [luigirizzo/netmap#174] opened 2016-05-10 17:31 UTC
Probem:
The utilization 1st goes up and then goes down. Using pkt-gen for 600 bytes packets read from pcap (pcap present in SSD). 5 extra extra_bufs and extra_pipes requested. Full Rate Tx requested.

The link saturates for a while and then goes down. Verified with speedometer -s -t eth<x> on another machine and external equipment as well.

![image](https://cloud.githubusercontent.com/assets/2750014/15155750/861748c4-1701-11e6-810c-a8d57a3b6173.png)

![image](https://cloud.githubusercontent.com/assets/2750014/15155949/79e2b6a0-1702-11e6-975f-a32b35a09cc2.png)

Linux: Ubuntu: 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

When netmap.ko is loaded: 320.781276 [3255] netmap_init               run mknod /dev/netmap c 10 57 # error 0

Test Bed : PowerEdge R430,
CPU: 2 x 1.6GHz Xeon E5-2603 v3
Memory: 48GB 1,600MHz DDR4 (max 384GB)
Storage: 2 x 1TB Dell 7.2K SATA hard disks + 1 500GB SSD (6 GBps)
RAID: Dell PERC S130
Array support: RAID0
Network: IXGBE (4.1.5 Patched)
Expansion: 2 x PCI-Express 3.0 slots

![image](https://cloud.githubusercontent.com/assets/2750014/15155842/e33d1628-1701-11e6-997c-253379f11213.png)

**Comment by vmaffione** [comment] 2016-05-10 20:27
From the log it's clear you are using the unpatched driver (generic netmap
adapter). Have you loaded the netmap-enabled ixgbe patched driver?
Moreover, what does it happen if you don't ask for extra_buffers and
extra_pipes?

2016-05-10 19:31 GMT+02:00 sibirchakraborty <notifications@github.com>:

> Probem:
> The utilization 1st goes up and then goes down. Using pkt-gen for 600
> bytes packets read from pcap (pcap present in SSD). 5 extra extra_bufs and
> extra_pipes requested. Full Rate Tx requested.
>
> The link saturates for a while and then goes down. Verified with
> speedometer -s -t eth on another machine and external equipment as well.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/2750014/15155750/861748c4-1701-11e6-810c-a8d57a3b6173.png>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/2750014/15155949/79e2b6a0-1702-11e6-975f-a32b35a09cc2.png>
>
> Linux: Ubuntu: 3.13.0-32-generic #57
> <https://github.com/luigirizzo/netmap/pull/57>-Ubuntu SMP Tue Jul 15
> 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
>
> When netmap.ko is loaded: 320.781276 [3255] netmap_init run mknod
> /dev/netmap c 10 57 # error 0
>
> Test Bed : PowerEdge R430,
> CPU: 2 x 1.6GHz Xeon E5-2603 v3
> Memory: 48GB 1,600MHz DDR4 (max 384GB)
> Storage: 2 x 1TB Dell 7.2K SATA hard disks + 1 500GB SSD (6 GBps)
> RAID: Dell PERC S130
> Array support: RAID0
> Network: IXGBE (4.1.5 Patched)
> Expansion: 2 x PCI-Express 3.0 slots
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/2750014/15155842/e33d1628-1701-11e6-997c-253379f11213.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/174>
>



-- 
Vincenzo Maffione

**Comment by sibirchakraborty** [comment] 2016-05-11 05:54
Hi,

Thanks for taking a look. The same happening with extra buffer.

Also, where should I download the patched driver from (for ixgbe)? Do I
have to patch manually. Do you have some place to download the patched
ixgbe drivers?

I am using https://github.com/pavel-odintsov/ixgbe-linux-netmap for ixgbe
patched drivers.

Regards,
Sibir

On Wed, May 11, 2016 at 1:57 AM, Vincenzo Maffione <notifications@github.com
> wrote:

> From the log it's clear you are using the unpatched driver (generic netmap
> adapter). Have you loaded the netmap-enabled ixgbe patched driver?
> Moreover, what does it happen if you don't ask for extra_buffers and
> extra_pipes?
>
> 2016-05-10 19:31 GMT+02:00 sibirchakraborty <notifications@github.com>:
>
> > Probem:
> > The utilization 1st goes up and then goes down. Using pkt-gen for 600
> > bytes packets read from pcap (pcap present in SSD). 5 extra extra_bufs
> and
> > extra_pipes requested. Full Rate Tx requested.
> >
> > The link saturates for a while and then goes down. Verified with
> > speedometer -s -t eth on another machine and external equipment as well.
> >
> > [image: image]
> > <
> https://cloud.githubusercontent.com/assets/2750014/15155750/861748c4-1701-11e6-810c-a8d57a3b6173.png
> >
> >
> > [image: image]
> > <
> https://cloud.githubusercontent.com/assets/2750014/15155949/79e2b6a0-1702-11e6-975f-a32b35a09cc2.png
> >
> >
> > Linux: Ubuntu: 3.13.0-32-generic #57
> > <https://github.com/luigirizzo/netmap/pull/57>-Ubuntu SMP Tue Jul 15
> > 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
> >
> > When netmap.ko is loaded: 320.781276 [3255] netmap_init run mknod
> > /dev/netmap c 10 57 # error 0
> >
> > Test Bed : PowerEdge R430,
> > CPU: 2 x 1.6GHz Xeon E5-2603 v3
> > Memory: 48GB 1,600MHz DDR4 (max 384GB)
> > Storage: 2 x 1TB Dell 7.2K SATA hard disks + 1 500GB SSD (6 GBps)
> > RAID: Dell PERC S130
> > Array support: RAID0
> > Network: IXGBE (4.1.5 Patched)
> > Expansion: 2 x PCI-Express 3.0 slots
> >
> > [image: image]
> > <
> https://cloud.githubusercontent.com/assets/2750014/15155842/e33d1628-1701-11e6-997c-253379f11213.png
> >
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/luigirizzo/netmap/issues/174>
> >
>
>
>
> --
> Vincenzo Maffione
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/174#issuecomment-218280590>
>



-- 
Thanks and regards,
Sibir

**Comment by vmaffione** [comment] 2016-05-11 08:51
Follow LINUX/README.
First you have to download the sources of your matching kernel. How to do this step depends on your distribution.
Then, you ./configure netmap making sure it finds those sources. If it does not find them automatically, you can use --kernel-sources and/or --kernel-dir as suggested by the ./configure output.
Then you make and keep following the README.

**Comment by sibirchakraborty** [comment] 2016-05-11 13:48
I have done that as well. The rates at that speed are far less:

![image](https://cloud.githubusercontent.com/assets/2750014/15183006/d605b4fa-17ac-11e6-8695-57f398f573af.png)

While insmod of ixgbe.ko

![image](https://cloud.githubusercontent.com/assets/2750014/15183020/e8c1a8e2-17ac-11e6-8713-0c769a16ed59.png)

Then I tested with using https://github.com/pavel-odintsov/ixgbe-linux-netmap for ixgbe
patched drivers.

He's drivers are from Version 4.1.5 and patched from netmap's supported patch I believe.

With that:
![image](https://cloud.githubusercontent.com/assets/2750014/15183079/2d5797fa-17ad-11e6-9153-7a10d051d267.png)


Please suggest.

**Comment by vmaffione** [comment] 2016-05-11 14:19
In order to narrow down the problem, please don't use extra buffers and use the latest commit in this repository.

In particular, use the following pkt-gen invocation to transmit on the IXGBE interface (ethX)
````
# ./pkt-gen -i ethX -f tx
````

Make sure to disable ethernet flow control

````
# ethtool -A ethX tx off rx off
````

There are two cases:

[1] Using the generic netmap adapter
````
# rmmod ixgbe
# modprobe ixgbe
# ifconfig ethX up
# ./pkt-gen -i ethX -f tx
````
In this case you should get something between 3Mpps and 4.5Mpps.

[2] Using the generic netmap adapter
````
# rmmod ixgbe
# insmod /path/to/netmap/src/LINUX/ixgbe/ixgbe.ko
# ifconfig ethX up
# ./pkt-gen -i ethX -f tx
````
In this case you should get something about 14 Mpps.

In your tests, I see different numbers, so there is something wrong.

**Comment by sibirchakraborty** [comment] 2016-05-11 14:29
Case 1:

![image](https://cloud.githubusercontent.com/assets/2750014/15184336/779f767a-17b2-11e6-8ff4-e2ebeeae964f.png)

![image](https://cloud.githubusercontent.com/assets/2750014/15184355/8b764412-17b2-11e6-9828-84bdda82a1a5.png)
![image](https://cloud.githubusercontent.com/assets/2750014/15184362/8f83f9aa-17b2-11e6-88ff-73101f385741.png)

Case 2:
![image](https://cloud.githubusercontent.com/assets/2750014/15184400/aba05282-17b2-11e6-89a6-94be061b6d0d.png)

![image](https://cloud.githubusercontent.com/assets/2750014/15184418/bfd0b008-17b2-11e6-90ec-11ae763179c2.png)
![image](https://cloud.githubusercontent.com/assets/2750014/15184439/cc7a12fe-17b2-11e6-8a4c-685f7dad335c.png)

Please advice.

**Comment by vmaffione** [comment] 2016-05-11 14:55
The results that I see are good for case 2 and also for case 1 (your machine is not very fast, so 1.2 Mpps with generic driver is ok).

For example, in case 2, I see pkt-gen reporting a stable tx rate (14.88 Mpps). Do you still see the oscillation if you let the test last for some times? Do you see the oscillation in the receiver only or also in the transmitter?

In any case, I still see in the log that you are using extra buffers.
````
netmap_extra_free ...
````
This should not show up if you follow the steps outlined above.

Are you sure you are using the latest commit 8123c744470aa4562635dd139d3895ed68d45dd7,
and that you are using the pkt-gen command I suggested?

**Comment by sibirchakraborty** [comment] 2016-05-11 15:08
Sorry I did not take the latest commit 8123c74 

pkt-gen I am using the same and when I did not get 10G speed, hence I allocated extra buffers. I have removed that.

BTW, what kind of hardware would you recommend to have full 10Gbps.

Right now oscillations are still there. I will take the latest commit and test:
![image](https://cloud.githubusercontent.com/assets/2750014/15185786/216f9bda-17b8-11e6-83b7-b41550ace15b.png)

![image](https://cloud.githubusercontent.com/assets/2750014/15185708/fba4b32c-17b7-11e6-928e-8eb8fe1b7a76.png)

**Comment by sibirchakraborty** [comment] 2016-05-12 18:32
Any inputs for this?

**Comment by vmaffione** [comment] 2016-05-14 13:12
Let's stick to the patched ixgbe case.

If I'm interpreting your Packets plot correctly, it is showing that you are receiving 4.5 (Mpps) Millions packets per second, which is inconsistent with the 14.8 Mpps pkt-gen is reporting on the transmit side.
So it may also be that your receiver system shows this spurious oscillation, and in that case netmap would not be the cause of this problem.

Try to log the output of pkt-gen for 5-10 minutes, to check if pkt-gen - the transmitter - reports sensible oscillation.

**Comment by sibirchakraborty** [comment] 2016-05-17 06:43
Right now oscillation are not much (~4%), which is fine in saturated link. Is there any way to improve Mpps for a generic driver somewhat higher than now?

**Comment by vmaffione** [comment] 2016-05-17 07:14
The purpose of the generic adapter is compatibility for netmap application: It allows to run netmap over any hardware or software interface (including taps, software bridges, veth, etc.). You could also use it with NICs up to 1 Gbit, since the maximum packet rate is often sustainable by the unpatched driver.

However, with 10 Gbit NICS (and faster ones) you need native netmap adapters - i.e. patched drivers.

In your case you are using ixgbe, for which the native adapter exists. Why do you want to downgrade to the generic adapter?

Using the generic adapter the bottleneck is the unpatched driver itself, so there is not that much you can do to improve performance. The only thing you can do is trying to set the generic_txqdisc netmap module parameter to 0, in order to use an alternative transmission scheme. But you should not get more than 3-5% improvement.

**Comment by sibirchakraborty** [comment] 2016-05-17 07:17
Actually ixgbe is fine, but there are Napatech adapters at 10G, for which no patch drivers exist. That's why. Do you have any such plans, or idea what are the things that needs to be patched

**Comment by vmaffione** [comment] 2016-05-17 07:58
Closing this.

Adding native netmap support for a NIC driver typically requires writing about ~600 lines of code, where the code structure is similar across different NICs. You have to write a register, txsync, rxsync and attach routine in a separate header file, to be included by the main driver source file. A  small patch is then necessary to the main driver source file to insert some "standard" glue code.

As an example, the ixgbe support consists of the following header LINUX/ixgbe_netmap_linux.h, and patch LINUX/final-patches/diff--ixgbe--31300--99999.

**Closed by vmaffione** 2016-05-17 07:58 UTC

**Comment by sibirchakraborty** [comment] 2016-05-17 11:56
![image](https://cloud.githubusercontent.com/assets/2750014/15321503/790fa628-1c54-11e6-9ad0-db02e7a4c03e.png)


Yes please close this.Thanks for all your help.
