### ISSUE TITLE
backward compatibility problem

### ISSUE THREAD

**Issue by ryanking8215** [luigirizzo/netmap#705] opened 2020-06-04 09:20 UTC
There seems to be a backward compatibility problem.

I tested two commits version of netmap
v1: 893e3740416 (current master)
v2: 9083fe492efc (early, about one month ago)

I built example with libnetmap by using v1. And insmod ko built by using v2. 
The example can't get the right slot , it is always the one previous to the correct one. (i.e. example get the slot and its len is not correct, and the one next to it is correct). 

vice verse.

specially， v1 breaks the compatibility with gonetmap (github.com/pragus/gonetmap)

**Comment by giuseppelettieri** [comment] 2020-06-04 10:03
Does this happen with any kind of netmap port, or only some of them (e.g., pipes)?

**Comment by giuseppelettieri** [comment] 2020-06-04 12:18
OK, I think I see where the problem is.

**Comment by giuseppelettieri** [comment] 2020-06-04 12:22
Does the following patch fixes the problem?
```
diff --git a/sys/net/netmap.h b/sys/net/netmap.h
index 6e213ef4..ed3c17f1 100644
--- a/sys/net/netmap.h
+++ b/sys/net/netmap.h
@@ -297,6 +297,13 @@ struct netmap_ring {
 
        struct timeval  ts;             /* (k) time of last *sync() */
 
+       /* opaque room for a mutex or similar object */
+#if !defined(_WIN32) || defined(__CYGWIN__)
+       uint8_t __attribute__((__aligned__(NM_CACHE_ALIGN))) sem[112];
+#else
+       uint8_t __declspec(align(NM_CACHE_ALIGN)) sem[112];
+#endif
+
        /* offset_mask is used to isolate the part of the ptr field
         * in the slots used to contain an offset in the buffer.
         * It is zero if the ring has not be opened using the
@@ -310,13 +317,6 @@ struct netmap_ring {
         */
        const uint64_t  buf_align;
 
-       /* opaque room for a mutex or similar object */
-#if !defined(_WIN32) || defined(__CYGWIN__)
-       uint8_t __attribute__((__aligned__(NM_CACHE_ALIGN))) sem[112];
-#else
-       uint8_t __declspec(align(NM_CACHE_ALIGN)) sem[112];
-#endif
-
        /* the slots follow. This struct has variable size */
        struct netmap_slot slot[0];     /* array of slots. */
 };
```

**Comment by ryanking8215** [comment] 2020-06-08 05:50
Sorry, how to patch correctly?
I checkout commit 893e374 (current master), and use `git apply xxx.patch`, which failed.
Or I tried `patch sys/net/netmap.h xxx.patch`, it failed too.

**Comment by giuseppelettieri** [comment] 2020-06-08 06:20
I have pushed some new commits that should fix the problem, so now there is no need to apply the patch. You can just test the latest master.

**Comment by ryanking8215** [comment] 2020-06-08 08:43
I test the new commits. It works. Thank you!

**Comment by giuseppelettieri** [comment] 2020-06-08 09:26
Perfect, we can close the issue then. Thanks for reporting!

**Closed by giuseppelettieri** 2020-06-08 09:26 UTC
